-- DROP SEQ & TABLE
DROP SEQUENCE GUEST_REVIEW_NO_SEQ;
DROP SEQUENCE HOST_REPLY_NO_SEQ;
DROP SEQUENCE HOST_CAMPGROUND_NO_SEQ;
DROP SEQUENCE GUEST_RESERVATION_NO_SEQ;
DROP SEQUENCE HOST_CAMPSITE_NO_SEQ;

DROP TABLE HOST_REPLY;
DROP TABLE GUEST_RESERVATION;
DROP TABLE GUEST_REVIEW;
DROP TABLE MEMBER_GUEST;
DROP TABLE GUEST_REVIEW;
DROP TABLE HOST_CAMPSITE;
DROP TABLE HOST_CAMPGROUND;
DROP TABLE MEMBER_HOST;


-- CREATE SEQ
CREATE SEQUENCE HOST_CAMPGROUND_NO_SEQ START WITH 111111 MINVALUE 111111 MAXVALUE 999999 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE GUEST_REVIEW_NO_SEQ START WITH 111111 MINVALUE 111111 MAXVALUE 999999 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE HOST_REPLY_NO_SEQ START WITH 111111 MINVALUE 111111 MAXVALUE 999999 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE GUEST_RESERVATION_NO_SEQ START WITH 111111 MINVALUE 111111 MAXVALUE 999999 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE HOST_CAMPSITE_NO_SEQ START WITH 111111 MINVALUE 111111 MAXVALUE 999999 NOCYCLE NOCACHE NOORDER;

-- CREATE TABLE
CREATE TABLE MEMBER_GUEST (
    S_GID VARCHAR2(15) PRIMARY KEY,
    S_GEMAIL VARCHAR2(30) NOT NULL UNIQUE,
    S_GPW VARCHAR2(40)NOT NULL,
    S_GNAME VARCHAR2(30) NOT NULL,
    S_GNICK VARCHAR2(100) NOT NULL,
    S_GTEL VARCHAR2(20) NOT NULL,
    S_GPHOTO VARCHAR2(100) NOT NULL,
    G_ADMIN_FLAG VARCHAR2(1) NOT NULL,
    G_DEL_YN VARCHAR2(1) NOT NULL,
    G_RDATE DATE NOT NULL
);

CREATE TABLE MEMBER_HOST (
    S_HID VARCHAR2(15) PRIMARY KEY,
    S_HEMAIL VARCHAR2(30) NOT NULL,
    S_HPW VARCHAR2(40) NOT NULL,
    S_HNAME VARCHAR2(30) NOT NULL,
    S_HTEL VARCHAR2(20) NOT NULL,
    S_HBIS_NAME VARCHAR2(100) NOT NULL,
    S_HBIS_NUM VARCHAR2(20) NOT NULL,
    S_HBIS_PIC VARCHAR2(100) NOT NULL,
    S_HADDR VARCHAR2(255) NOT NULL,
    S_HACC_BANKNAME VARCHAR2(30) NOT NULL,
    S_HACCOUNT VARCHAR2(30) NOT NULL,
    S_HACC_PIC VARCHAR2(100) NOT NULL,
    S_HPIC VARCHAR2(100) NOT NULL,
    H_DEL_YN VARCHAR2(1) NOT NULL,
    H_OK_YN VARCHAR2(1) NOT NULL,
    H_RDATE DATE NOT NULL
);


CREATE TABLE HOST_CAMPGROUND (
    S_CAMP_NO VARCHAR2(20) PRIMARY KEY,
    S_CAMP_NAME VARCHAR2(50) NOT NULL,
    S_CAMP_DESC VARCHAR2(255) NOT NULL,
    S_CAMP_ADDR VARCHAR2(255) NOT NULL,
    S_CAMP_TEL VARCHAR2(20) NOT NULL,
    S_HID VARCHAR2(15) NOT NULL,
    S_CAMP_MAINPIC VARCHAR2(100) NOT NULL, -- 메인 사진 필수
    S_CAMP_MAPPIC VARCHAR2(100) NOT NULL, -- 지도 사진 필수
    S_CAMP_PIC1 VARCHAR2(100) NOT NULL, 
    S_CAMP_PIC2 VARCHAR2(100) NOT NULL, -- 사진 2장 이상 5장 미만 필수
    S_CAMP_PIC3 VARCHAR2(100),
    S_CAMP_PIC4 VARCHAR2(100),
    S_CAMP_PIC5 VARCHAR2(100), 
    S_BATHROOM VARCHAR2(1) NOT NULL,
    S_SHOWERBOOTH VARCHAR2(1) NOT NULL,
    S_STORE VARCHAR2(1) NOT NULL,
    S_SINK VARCHAR2(1) NOT NULL,
    S_WIFI VARCHAR2(1) NOT NULL,
    S_PLAYGROUND VARCHAR2(1) NOT NULL,
    S_WITH_PET VARCHAR2(1) NOT NULL,
    S_SWIM_POOL VARCHAR2(1) NOT NULL, 
    CG_DEL_YN VARCHAR2(1) NOT NULL,
    CG_RDATE DATE NOT NULL, 
    FOREIGN KEY (S_HID) REFERENCES MEMBER_HOST (S_HID)
);

CREATE TABLE HOST_CAMPSITE (
    S_SITE_NO VARCHAR2(20) PRIMARY KEY,
    S_CAMP_NO VARCHAR2(20) NOT NULL,
    S_SITENAME VARCHAR2(30) NOT NULL,
    S_SITEPRICE NUMBER(8) NOT NULL,
    CS_DEL_YN VARCHAR2(1) NOT NULL,
    CS_RDATE DATE NOT NULL,
    FOREIGN KEY (S_CAMP_NO) REFERENCES HOST_CAMPGROUND (S_CAMP_NO)
);


CREATE TABLE GUEST_RESERVATION(
    S_REZ_NO VARCHAR2(20) PRIMARY KEY,
    S_SITE_NO VARCHAR2(20) NOT NULL,
    D_SELECT DATE NOT NULL,
    S_GID VARCHAR2(15) NOT NULL,
    D_REZ_DATE DATE NOT NULL,
    GR_STATUS VARCHAR2(1) NOT NULL,
    FOREIGN KEY (S_GID) REFERENCES MEMBER_GUEST (S_GID),
    FOREIGN KEY (S_SITE_NO) REFERENCES HOST_CAMPSITE (S_SITE_NO)
);

CREATE TABLE GUEST_REVIEW (
    I_REV_NO NUMBER(6) PRIMARY KEY,
    S_CAMP_NO VARCHAR2(20) NOT NULL,
    S_GID VARCHAR2(15) NOT NULL,
    S_REV_TITLE VARCHAR2(255) NOT NULL,
    S_REV_CONTENT CLOB NOT NULL,
    D_RDATE DATE NOT NULL,
    S_REV_IP VARCHAR2(30) NOT NULL,
    S_REV_MAINPIC VARCHAR2(100),
    S_REV_PIC1 VARCHAR2(100),
    S_REV_PIC2 VARCHAR2(100),
    S_REV_PIC3 VARCHAR2(100),
    FOREIGN KEY (S_GID) REFERENCES MEMBER_GUEST(S_GID),
    FOREIGN KEY (S_CAMP_NO) REFERENCES HOST_CAMPGROUND(S_CAMP_NO)
);

CREATE TABLE HOST_REPLY(
    I_REP_NO NUMBER(6) PRIMARY KEY,
    S_REP_CONTENT VARCHAR2(4000) NOT NULL,
    S_CAMP_NO VARCHAR2(20) NOT NULL,
    I_REV_NO NUMBER(6) NOT NULL,
    S_HID VARCHAR2(15) NOT NULL,
    S_REP_IP VARCHAR2(30) NOT NULL,
    RP_RDATE DATE NOT NULL,
    FOREIGN KEY (S_CAMP_NO) REFERENCES HOST_CAMPGROUND (S_CAMP_NO),
    FOREIGN KEY (I_REV_NO) REFERENCES GUEST_REVIEW (I_REV_NO) ON DELETE CASCADE,
    FOREIGN KEY (S_HID) REFERENCES MEMBER_HOST (S_HID)
);

COMMIT;

SELECT * FROM HOST_CAMPSITE;
CREATE OR REPLACE TRIGGER HOST_DEL
AFTER UPDATE OF H_DEL_YN ON MEMBER_HOST
BEGIN
    UPDATE HOST_CAMPGROUND SET CG_DEL_YN = 'Y';
    UPDATE HOST_CAMPSITE SET CS_DEL_YN = 'Y';
END;